### Root endpoint
GET http://{{ host }}/
Accept: application/json

### Test liveness probe
GET http://{{ host }}/healthz
Accept: application/json

### Get all articles
GET http://{{ host }}/article/

### Add article
POST http://{{ host }}/article/
Content-Type: application/json

{
  "name": "Article 1",
  "description": "The best article of all times"
}

### Remove article
@articleId = 6583018ff228b3e5cf8dfabe
DELETE http://{{ host }}/article/{{ articleId }}/
Accept: application/json
