version: '3'
services:

  mongo:
    image: mongo:4

  redis:
    image: redis:6

  api-cart:
    #image: alphayax/microservice-demo-cart-service:latest
    build:
      context: ./cart-service
    environment:
      REDIS_URI: "redis://redis:6379"
    depends_on:
      - redis

  api-article:
    #image: alphayax/microservice-demo-article-service:latest
    build:
      context: ./article-service
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo

  front-admin:
    #image: alphayax/microservice-demo-frontend-admin:latest
    build:
      context: ./front-admin

  front-client:
    #image: alphayax/microservice-demo-frontend-user:latest
    build:
      context: ./front-user

  ingress:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./.compose/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-cart
      - api-article
      - front-admin
      - front-client
